# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run lint and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install pdoc3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
    - name: Test and code coverage with custom test engine
      run: |
        python -m coverage run -m src.main -e ALL
        codeCoverageStr=$(python -m coverage report | grep 'TOTAL')
        codeCoverage=$(echo $codeCoverageStr | awk '{print $4}')
        echo "Code coverage: $codeCoverage"
        failureStr=$(python -m src.main -e ALL | grep -i "Number of failed tests:")
        numFailures=${failureStr:0-1}
        if [ $numFailures -gt 1 ]; then exit $numFailures; else exit 0; fi       
    
